kubectl create secret generic s1 --from-literal=dbname=db1 --from-literal=dbpasswd=123
=================
apiVersion: v1
kind: Pod
metadata:
  name: db3
  namespace: default
  labels:
    cm: cm1
spec:
  containers:
  - name: c1
    image: docker.io/mysql
    env:
    - name: MYSQL_DATABASE
      valueFrom:
        secretKeyRef:
          name: secret2
          key: MYSQL_DATABASE
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: secret2
          key: MYSQL_ROOT_PASSWORD
