---
apiVersion: v1
kind: Service
metadata:
  name: s1
  labels:
    app: nginx
spec:
  ports:
  - port: 3306
  clusterIP: None
  selector:
    app: db1
...
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: db1
  name: db1

spec:
  serviceName: "s1"
  replicas: 1
  selector:
    matchLabels:
      app: db1

  template:
    metadata:

      labels:
        app: db1
    spec:
      containers:
      - image: mysql
        name: mysql
        env:
        - name: MYSQL_DATABASE
          value: 'db1'
        - name: MYSQL_ROOT_PASSWORD
          value: '123'
        volumeMounts:
        - name: v1
          mountPath: /var/lib/mysql 
      
      volumes:
      - name: v1
        persistentVolumeClaim:
          claimName: pvc1
